"""Metadata enriching the canonical runtime signal vocabulary."""

from battery_sim.core.result import Signal

_SIGNAL_METADATA: dict = {
    Signal.TIME: {
        "unit": "s",
        "interpretation": "Simulation time axis shared by all time-series signals.",
        "use_cases": ["plotting", "alignment", "transient_analysis"],
        "typical_range": "Starts at 0 s and increases monotonically",
    },
    Signal.VOLTAGE: {
        "unit": "V",
        "interpretation": "Cell terminal voltage. Decreases as battery discharges.",
        "use_cases": ["safety_monitoring", "efficiency_analysis", "protocol_feasibility"],
        "typical_range": "2.5V - 4.2V for lithium cells",
        "aliases": ["voltage_V"],
    },
    Signal.CURRENT: {
        "unit": "A",
        "interpretation": "Discharge current (positive) or charge current (negative).",
        "use_cases": ["power_analysis", "safety_monitoring", "thermal_analysis"],
        "typical_range": "Positive during discharge, proportional to C-rate",
        "aliases": ["current_A"],
    },
    Signal.POWER: {
        "unit": "W",
        "interpretation": "Instantaneous power derived from voltage and current.",
        "use_cases": ["peak_power_applications", "efficiency_analysis", "thermal_analysis"],
        "typical_range": "Depends on capacity and C-rate",
        "aliases": ["power_W"],
    },
    Signal.ENERGY: {
        "unit": "Wh",
        "interpretation": "Cumulative energy delivered over the simulation.",
        "use_cases": ["capacity_validation", "efficiency_analysis", "cycle_comparison"],
        "typical_range": "0 to nominal capacity (Ah) × nominal voltage (V)",
        "aliases": ["energy_Wh"],
    },
    Signal.SOC: {
        "unit": "%",
        "interpretation": "Battery charge level (0% = empty, 100% = full).",
        "use_cases": ["bms_calibration", "remaining_range_estimation", "safety_limits"],
        "typical_range": "0% - 100%",
        "aliases": ["state_of_charge_percent"],
    },
    Signal.SOH: {
        "unit": "%",
        "interpretation": "State of health estimate for degradation-aware workflows.",
        "use_cases": ["aging_analysis", "fleet_monitoring", "maintenance_planning"],
        "typical_range": "Typically near 100% for a fresh cell",
    },
    Signal.CAPACITY: {
        "unit": "Ah",
        "interpretation": "Cumulative charge throughput derived from current over time.",
        "use_cases": ["capacity_validation", "cycle_comparison", "aging_analysis"],
        "typical_range": "0 to nominal cell capacity for a full discharge",
    },
    Signal.CAPACITY_FADE: {
        "unit": "%",
        "interpretation": "Capacity loss relative to the initial reference capacity.",
        "use_cases": ["aging_analysis", "warranty_tracking", "cycle_life_prediction"],
        "typical_range": "0% for a fresh cell and increases with degradation",
    },
    Signal.TEMPERATURE: {
        "unit": "°C",
        "interpretation": "Cell temperature during operation, distinct from ambient input temperature.",
        "use_cases": ["thermal_analysis", "safety_monitoring", "cycle_life_prediction"],
        "typical_range": "20°C - 60°C typical for safe operation",
        "aliases": ["temperature_C"],
    },
    Signal.HEAT_GENERATION: {
        "unit": "W",
        "interpretation": "Instantaneous heat generation rate produced by electrochemical losses.",
        "use_cases": ["thermal_management", "cooling_requirements", "safety_limits"],
        "typical_range": "Depends on current, resistance, and operating point",
    },
    Signal.IRREVERSIBLE_HEAT: {
        "unit": "W/m³",
        "interpretation": "Heat from Butler-Volmer overpotential losses (irreversible electrochemical heating).",
        "use_cases": ["thermal_analysis", "loss_decomposition"],
        "typical_range": "Model-dependent, increases with C-rate",
    },
    Signal.REVERSIBLE_HEAT: {
        "unit": "W/m³",
        "interpretation": "Entropic heat contribution from OCV temperature dependence.",
        "use_cases": ["thermal_analysis", "loss_decomposition"],
        "typical_range": "Can be positive or negative depending on SOC",
    },
    Signal.OHMIC_HEAT: {
        "unit": "W/m³",
        "interpretation": "Joule heating (I²R) in electrolyte and solid phases.",
        "use_cases": ["thermal_analysis", "loss_decomposition"],
        "typical_range": "Scales with current squared",
    },
    Signal.CELL_TEMPERATURE: {
        "unit": "°C",
        "interpretation": "X-averaged cell temperature, distinct from ambient temperature input.",
        "use_cases": ["thermal_analysis", "safety_monitoring", "thermal_model_validation"],
        "typical_range": "20°C - 60°C typical for safe operation",
    },
    Signal.ANODE_POTENTIAL: {
        "unit": "V",
        "interpretation": "Negative electrode potential available on detailed models.",
        "use_cases": ["dfn_diagnostics", "electrode_analysis"],
        "typical_range": "Model-dependent",
    },
    Signal.CATHODE_POTENTIAL: {
        "unit": "V",
        "interpretation": "Positive electrode potential available on detailed models.",
        "use_cases": ["dfn_diagnostics", "electrode_analysis"],
        "typical_range": "Model-dependent",
    },
    Signal.OVERPOTENTIAL: {
        "unit": "V",
        "interpretation": "Electrochemical overpotential generated by polarization losses.",
        "use_cases": ["loss_analysis", "fast_charge_diagnostics"],
        "typical_range": "Model-dependent",
    },
    Signal.ELECTROLYTE_CONCENTRATION: {
        "unit": "mol.m-3",
        "interpretation": "Electrolyte concentration state, mainly for DFN-style analysis.",
        "use_cases": ["dfn_diagnostics", "transport_analysis"],
        "typical_range": "Model-dependent",
    },
    Signal.INTERNAL_RESISTANCE: {
        "unit": "Ω",
        "interpretation": "Effective internal resistance inferred from voltage and current.",
        "use_cases": ["model_degradation", "cycle_prediction", "aging_analysis"],
        "typical_range": "0.01Ω - 0.5Ω depending on chemistry",
        "aliases": ["internal_resistance_Ohm"],
    },
    Signal.EFFICIENCY: {
        "unit": "%",
        "interpretation": "Efficiency metric derived from delivered and stored energy.",
        "use_cases": ["battery_selection", "system_design", "cost_optimization"],
        "typical_range": "85% - 99% depending on chemistry",
        "aliases": ["charge_discharge_efficiency_percent", "round_trip_efficiency_percent"],
    },
    Signal.CYCLE_DISCHARGE_CAPACITY: {
        "unit": "Ah",
        "interpretation": "Per-cycle discharge capacity. Time axis is cycle number.",
        "use_cases": ["aging_analysis", "cycle_life_prediction", "capacity_validation"],
        "typical_range": "Depends on cell capacity and protocol",
    },
    Signal.CYCLE_CHARGE_CAPACITY: {
        "unit": "Ah",
        "interpretation": "Per-cycle charge capacity. Time axis is cycle number.",
        "use_cases": ["aging_analysis", "cycle_life_prediction", "capacity_validation"],
        "typical_range": "Depends on cell capacity and protocol",
    },
    Signal.CYCLE_COULOMBIC_EFFICIENCY: {
        "unit": "%",
        "interpretation": "Per-cycle coulombic efficiency (discharge capacity / charge capacity).",
        "use_cases": ["aging_analysis", "degradation_diagnostics", "quality_control"],
        "typical_range": "95% - 100% for healthy cells",
    },
    Signal.CYCLE_CAPACITY_RETENTION: {
        "unit": "%",
        "interpretation": "Per-cycle capacity retention relative to first cycle.",
        "use_cases": ["aging_analysis", "warranty_tracking", "cycle_life_prediction"],
        "typical_range": "100% initially, decreasing with age",
    },
    Signal.SEI_THICKNESS: {
        "unit": "m",
        "interpretation": "X-averaged SEI layer thickness on the negative electrode.",
        "use_cases": ["aging_analysis", "degradation_monitoring", "cycle_life_prediction"],
        "typical_range": "Grows from ~5nm; model-dependent",
    },
    Signal.LITHIUM_PLATING_CAPACITY: {
        "unit": "A.h",
        "interpretation": "Cumulative capacity lost to lithium plating on the negative electrode.",
        "use_cases": ["fast_charge_diagnostics", "safety_monitoring", "degradation_monitoring"],
        "typical_range": "0 for no plating; increases with fast charging or low temps",
    },
    Signal.LOSS_OF_ACTIVE_MATERIAL: {
        "unit": "%",
        "interpretation": "Percentage of active material lost in the negative electrode.",
        "use_cases": ["aging_analysis", "degradation_monitoring", "warranty_tracking"],
        "typical_range": "0% fresh cell; increases with mechanical stress cycling",
    },
    Signal.TOTAL_CAPACITY_LOSS: {
        "unit": "A.h",
        "interpretation": "Total capacity lost to all side reactions (SEI, plating, etc.).",
        "use_cases": ["aging_analysis", "degradation_monitoring", "cycle_life_prediction"],
        "typical_range": "0 for fresh cell; accumulates over cycling",
    },
    Signal.SEI_FILM_RESISTANCE: {
        "unit": "Ω·m²",
        "interpretation": "X-averaged SEI film resistance. Increases as the SEI layer grows, contributing to impedance rise.",
        "use_cases": ["aging_analysis", "impedance_diagnostics", "degradation_monitoring"],
        "typical_range": "Model-dependent; increases with SEI thickness",
    },
    Signal.LITHIUM_PLATING_THICKNESS: {
        "unit": "m",
        "interpretation": "X-averaged lithium plating thickness on the negative electrode surface.",
        "use_cases": ["fast_charge_diagnostics", "safety_monitoring", "degradation_monitoring"],
        "typical_range": "0 for no plating; increases at low temps or high charge rates",
    },
    Signal.NEGATIVE_PARTICLE_CRACK_LENGTH: {
        "unit": "m",
        "interpretation": "X-averaged crack length in negative electrode particles due to mechanical stress during cycling.",
        "use_cases": ["mechanical_degradation", "aging_analysis", "coupled_degradation"],
        "typical_range": "Starts at initial crack length; grows with cycling stress",
    },
    # Phase B: Deep electrochemical observability signals
    Signal.NEGATIVE_PARTICLE_SURFACE_CONCENTRATION: {
        "unit": "mol/m³",
        "interpretation": "X-averaged lithium concentration at the negative particle surface. Indicates how much lithium is available at the reaction interface.",
        "use_cases": ["electrode_analysis", "transport_diagnostics", "fast_charge_analysis"],
        "typical_range": "0 to c_s,max (~30000 mol/m³ for graphite)",
    },
    Signal.POSITIVE_PARTICLE_SURFACE_CONCENTRATION: {
        "unit": "mol/m³",
        "interpretation": "X-averaged lithium concentration at the positive particle surface. Reflects cathode utilization.",
        "use_cases": ["electrode_analysis", "transport_diagnostics", "fast_charge_analysis"],
        "typical_range": "0 to c_s,max (~50000 mol/m³ for NMC)",
    },
    Signal.NEGATIVE_OCV: {
        "unit": "V",
        "interpretation": "Negative electrode open-circuit potential vs Li/Li+. Determined by stoichiometry via the OCV curve.",
        "use_cases": ["voltage_decomposition", "electrode_analysis", "dfn_diagnostics"],
        "typical_range": "0.05V - 1.0V for graphite",
    },
    Signal.POSITIVE_OCV: {
        "unit": "V",
        "interpretation": "Positive electrode open-circuit potential vs Li/Li+. Determined by stoichiometry via the OCV curve.",
        "use_cases": ["voltage_decomposition", "electrode_analysis", "dfn_diagnostics"],
        "typical_range": "3.0V - 4.5V for NMC",
    },
    Signal.NEGATIVE_REACTION_OVERPOTENTIAL: {
        "unit": "V",
        "interpretation": "Butler-Volmer reaction overpotential at the negative electrode. Drives the intercalation reaction rate.",
        "use_cases": ["voltage_decomposition", "loss_analysis", "fast_charge_diagnostics"],
        "typical_range": "Typically millivolts to tens of millivolts",
    },
    Signal.POSITIVE_REACTION_OVERPOTENTIAL: {
        "unit": "V",
        "interpretation": "Butler-Volmer reaction overpotential at the positive electrode. Drives the intercalation reaction rate.",
        "use_cases": ["voltage_decomposition", "loss_analysis", "fast_charge_diagnostics"],
        "typical_range": "Typically millivolts to tens of millivolts",
    },
    Signal.NEGATIVE_EXCHANGE_CURRENT_DENSITY: {
        "unit": "A/m²",
        "interpretation": "Exchange current density at the negative electrode. Controls Butler-Volmer reaction kinetics; depends on concentration and temperature.",
        "use_cases": ["kinetics_analysis", "fast_charge_diagnostics", "temperature_sensitivity"],
        "typical_range": "Model-dependent, typically 1-100 A/m²",
    },
    Signal.POSITIVE_EXCHANGE_CURRENT_DENSITY: {
        "unit": "A/m²",
        "interpretation": "Exchange current density at the positive electrode. Controls Butler-Volmer reaction kinetics; depends on concentration and temperature.",
        "use_cases": ["kinetics_analysis", "fast_charge_diagnostics", "temperature_sensitivity"],
        "typical_range": "Model-dependent, typically 1-100 A/m²",
    },
    Signal.ELECTROLYTE_POTENTIAL: {
        "unit": "V",
        "interpretation": "X-averaged electrolyte potential. Available in SPMe/DFN models where electrolyte transport is resolved.",
        "use_cases": ["voltage_decomposition", "transport_analysis", "dfn_diagnostics"],
        "typical_range": "Model-dependent",
    },
    Signal.NEGATIVE_STOICHIOMETRY: {
        "unit": "-",
        "interpretation": "Negative electrode stoichiometry θ = c_s/c_s,max. Local 'filling fraction' of lithium in the graphite particle.",
        "use_cases": ["electrode_analysis", "soc_mapping", "voltage_decomposition"],
        "typical_range": "0 (empty) to 1 (full); ~0.9 at full charge for graphite",
    },
    Signal.POSITIVE_STOICHIOMETRY: {
        "unit": "-",
        "interpretation": "Positive electrode stoichiometry θ = c_s/c_s,max. Local 'filling fraction' of lithium in the cathode particle.",
        "use_cases": ["electrode_analysis", "soc_mapping", "voltage_decomposition"],
        "typical_range": "0 (empty) to 1 (full); ~0.5 at full charge for NMC",
    },
    Signal.NEGATIVE_SOLID_POTENTIAL: {
        "unit": "V",
        "interpretation": "X-averaged negative electrode solid-phase potential. The electron potential in the solid matrix.",
        "use_cases": ["electrode_analysis", "voltage_decomposition", "dfn_diagnostics"],
        "typical_range": "Model-dependent, typically near negative OCV",
    },
    Signal.POSITIVE_SOLID_POTENTIAL: {
        "unit": "V",
        "interpretation": "X-averaged positive electrode solid-phase potential. The electron potential in the solid matrix.",
        "use_cases": ["electrode_analysis", "voltage_decomposition", "dfn_diagnostics"],
        "typical_range": "Model-dependent, typically near positive OCV",
    },
}
